### ISSUE TITLE
Use the default configuration to create a file invalid

### ISSUE THREAD

**Issue by xYx-c** [VincentBerthier/auto-header.nvim#1] opened 2023-03-06 01:57 UTC
The map key to add header can work 

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

**Comment by vincentberthier** [comment] 2023-03-06 15:46
I'm sorry did you mean that the mapped key doesn't work as it is?

**Comment by xYx-c** [comment] 2023-03-16 03:05
Header information will not be added directly after creating a new file, and key mapping needs to be actively used
Can it be possible to automatically add header information when creating a new file?

**Comment by vincentberthier** [comment] 2023-06-29 18:04
Hmm, I was about to say that it might be because you forgot something in the configuration because I don’t have this problem.

But… apparently the problem is that I commented the line that sets this up automatically… My bad, it should be fixed now.

**Closed as completed** 2023-08-05 21:17 UTC
